trigger:
  branches:
    include:
      - main  # Automatically trigger the pipeline when pushing to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the pipeline

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Use Node.js version 16
  displayName: 'Install Node.js'

- script: |
    npm install  # Install dependencies
    npm run test  # Run any tests you’ve defined (for now, this does nothing)
  displayName: 'Install dependencies and run tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive application files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'  # Name of the artifact
  displayName: 'Publish build artifacts'

